title: Streamdata Gallery Google Cloud Identity Access Management
url: google-cloud-identity-access-management.streamdata.gallery
tag: Google Cloud Identity Access Management
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: google-cloud-identity-access-management
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
